//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pff2
{
    using System;
    using System.Collections.Generic;
    
    public partial class complexe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public complexe()
        {
            this.EFPs = new HashSet<EFP>();
        }
    
        public string code_c { get; set; }
        public string nom_c { get; set; }
        public string adresse { get; set; }
        public string ville { get; set; }
        public string code_postale { get; set; }
        public string codedrfk { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
    
        public virtual dr dr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFP> EFPs { get; set; }
    }
}
