//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pff2
{
    using System;
    using System.Collections.Generic;
    
    public partial class formateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public formateur()
        {
            this.AffectationFMGs = new HashSet<AffectationFMG>();
        }
    
        public string mlle { get; set; }
        public string Nom { get; set; }
        public string prenom { get; set; }
        public Nullable<System.DateTime> dateNaissance { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public string codePostal { get; set; }
        public string region { get; set; }
        public string GSM { get; set; }
        public string Email { get; set; }
        public string codeSFk { get; set; }
        public string filierprincipal { get; set; }
        public string EFPPrincipale { get; set; }
        public string categorie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffectationFMG> AffectationFMGs { get; set; }
        public virtual EFP EFP { get; set; }
        public virtual filier filier { get; set; }
        public virtual secteur secteur { get; set; }
    }
}
