//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pff2
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public groupe()
        {
            this.AffectationFMGs = new HashSet<AffectationFMG>();
            this.stagaires = new HashSet<stagaire>();
        }
    
        public int codeGroupe { get; set; }
        public string codeEFPFK { get; set; }
        public string codeFFk { get; set; }
        public string annee { get; set; }
        public int niveau { get; set; }
        public Nullable<int> capaciteMax { get; set; }
        public Nullable<int> countt { get; set; }
        public string Responsable1 { get; set; }
        public string Responsable2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffectationFMG> AffectationFMGs { get; set; }
        public virtual FEFP FEFP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stagaire> stagaires { get; set; }
        public virtual stagaire stagaire { get; set; }
        public virtual stagaire stagaire1 { get; set; }
    }
}
