//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pff2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projetffEntities : DbContext
    {
        public projetffEntities()
            : base("name=projetffEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absence> Absences { get; set; }
        public virtual DbSet<AffectationFMG> AffectationFMGs { get; set; }
        public virtual DbSet<complexe> complexes { get; set; }
        public virtual DbSet<dr> drs { get; set; }
        public virtual DbSet<EFP> EFPs { get; set; }
        public virtual DbSet<FEFP> FEFPs { get; set; }
        public virtual DbSet<filier> filiers { get; set; }
        public virtual DbSet<formateur> formateurs { get; set; }
        public virtual DbSet<groupe> groupes { get; set; }
        public virtual DbSet<module> modules { get; set; }
        public virtual DbSet<ObjectifSeance> ObjectifSeances { get; set; }
        public virtual DbSet<seance> seances { get; set; }
        public virtual DbSet<secteur> secteurs { get; set; }
        public virtual DbSet<stagaire> stagaires { get; set; }
    }
}
