//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pff2
{
    using System;
    using System.Collections.Generic;
    
    public partial class module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public module()
        {
            this.AffectationFMGs = new HashSet<AffectationFMG>();
        }
    
        public int numeroM { get; set; }
        public string codeffk { get; set; }
        public string nom_m { get; set; }
        public string descriptionn { get; set; }
        public Nullable<int> chs1 { get; set; }
        public Nullable<double> coefs1 { get; set; }
        public Nullable<int> chs2 { get; set; }
        public Nullable<double> coefs2 { get; set; }
        public Nullable<int> chs3 { get; set; }
        public Nullable<double> coefs3 { get; set; }
        public Nullable<int> chs4 { get; set; }
        public Nullable<double> coefs4 { get; set; }
        public Nullable<int> chs5 { get; set; }
        public Nullable<double> coefs5 { get; set; }
        public Nullable<int> chs6 { get; set; }
        public Nullable<double> coefs6 { get; set; }
        public string type_m { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffectationFMG> AffectationFMGs { get; set; }
        public virtual filier filier { get; set; }
    }
}
