//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pff2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectifSeance
    {
        public int numObjectif { get; set; }
        public string FormateurFK { get; set; }
        public Nullable<int> numModuleFk { get; set; }
        public string codeFFk1 { get; set; }
        public Nullable<int> codeGroupe { get; set; }
        public string codeEFPFK { get; set; }
        public string codeFFk2 { get; set; }
        public string annee { get; set; }
        public Nullable<int> niveau { get; set; }
        public Nullable<int> Semestre { get; set; }
        public Nullable<System.DateTime> DateS { get; set; }
        public string heureDepart { get; set; }
        public string heureFin { get; set; }
        public string Description { get; set; }
        public string typee { get; set; }
    
        public virtual seance seance { get; set; }
    }
}
