//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pff2
{
    using System;
    using System.Collections.Generic;
    
    public partial class seance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seance()
        {
            this.Absences = new HashSet<Absence>();
            this.ObjectifSeances = new HashSet<ObjectifSeance>();
        }
    
        public string FormateurFK { get; set; }
        public int numModuleFk { get; set; }
        public string codeFFk1 { get; set; }
        public int codeGroupe { get; set; }
        public string codeEFPFK { get; set; }
        public string codeFFk2 { get; set; }
        public string annee { get; set; }
        public int niveau { get; set; }
        public int semestre { get; set; }
        public System.DateTime dateS { get; set; }
        public string heurDepart { get; set; }
        public string heureFin { get; set; }
        public string Salle { get; set; }
        public Nullable<double> Cumul { get; set; }
        public Nullable<double> Durée { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Absence> Absences { get; set; }
        public virtual AffectationFMG AffectationFMG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectifSeance> ObjectifSeances { get; set; }
    }
}
